require:
  - rubocop-performance
  - rubocop-rspec

inherit_gem:
  rentacop: rentacop.yml

AllCops:
  TargetRubyVersion: 2.7
  SuggestExtensions: false

# The `ConfigValidator` class is a DSL, give it some complexity leeway
Metrics/AbcSize:
  Exclude:
  - lib/bashly/config_validator.rb

# (same as previous rule)
Metrics/CyclomaticComplexity:
  Exclude:
  - lib/bashly/config_validator.rb

# (same as previous rule)
Metrics/PerceivedComplexity:
  Exclude:
  - lib/bashly/config_validator.rb

# (same as previous rule)
Metrics/MethodLength:
  Exclude:
  - lib/bashly/config_validator.rb

# Guard clauses are less readable in the case of `ConfigValidator` 
Style/GuardClause:
  Exclude:
  - lib/bashly/config_validator.rb

# Commands may include long lines
Layout/LineLength:
  Exclude:
    - 'lib/bashly/commands/*'

# Prefer `receive` over `have_received` spies
RSpec/MessageSpies:
  EnforcedStyle: receive

# Allow unnamed subjects
RSpec/NamedSubject:
  Enabled: false

# Allow the first `describe` to be arbitrary
RSpec/DescribeClass:
  Enabled: false

# Allow longer tests
RSpec/ExampleLength:
  Max: 8

# Allow multiple expectations
RSpec/MultipleExpectations:
  Max: 3

# Allow more `let` per test
RSpec/MultipleMemoizedHelpers:
  Max: 8

# Allow nested groups
RSpec/NestedGroups:
  Max: 4

# Allow `expect` in `before` hook, it is used as a utility to trap output and
# ensure state
RSpec/ExpectInHook:
  Enabled: false

# Allow irregular filenames in some cases
RSpec/FilePath:
  Exclude:
    - 'spec/bashly/concerns/completions_command_spec.rb'
    - 'spec/bashly/concerns/completions_flag_spec.rb'