name: Test
on:
  pull_request:
  push: { branches: master }

jobs:
  test:
    name: Ruby ${{ matrix.ruby }}

    runs-on: ubuntu-latest

    env: 
      # For consistent sort order
      LC_ALL: en_US.UTF-8 

    strategy:
      matrix: { ruby: ['2.7', '3.0', '3.1', 'head'] }

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    # libyaml needed for Ruby's YAML library
    - name: Install OS dependencies
      run: sudo apt-get -y install libyaml-dev

    # Rush needed for easy installation of latest shfmt
    - name: Install rush
      run: curl -Ls http://get.dannyb.co/rush/setup | bash

    - name: Install shfmt
      run: rush snatch dannyben/shfmt

    - name: Setup Ruby
      uses: ruby/setup-ruby@v1
      with: 
        ruby-version: '${{ matrix.ruby }}'
        bundler-cache: true

    - name: Run tests
      run: bundle exec rspec

    - name: Run shellcheck tests
      run: bundle exec run shellcheck

    - name: Run shfmt tests
      run: bundle exec run shfmt
